@host=https://localhost:7085

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Tidiane",
    "lastName": "DIALLO",
    "email": "diallotidiane014@gmail.com",
    "password":"Passe@0#"
}